### PR TITLE
Fix: x-axis ticks from overlapping (fixes: #32)

### PR DESCRIPTION
**Pull request by pranav300**
**What is the purpose of this pull request? (put an "X" next to item)**

- [ ] Documentation update
- [ ] Bug fix
- [ ] New functionality
- [x]  Changes an existing functionality
- [ ] Other, please explain:

**What changes did you make? (Give an overview)**
I have changed `Max_Tick_variance`, So that x-axis ticks do not overlap on each other. This is a temporary fix. This would work only on dynamic ticks, but the overlapping depends upon the size of ticks.
I will be working on issues #22 and #9 to resolve this.

### CODE REVIEW

**Comment by abhijit945** [comment]
Can you add a screenshot with the X Axis datetime range having months instead and show the fix is valid? Thanks.

**Comment by pranav300** [comment]
This is the closest 31st and 1st get.

Screenshot 2019-09-18 at 7 40 39 PM

**Comment by abhijit945** [comment]
You need to also add the term `(fixes #32)` in the commit message to actually close the issue.

**Pull request merged**
